# Generated by Django 4.2.6 on 2023-10-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='technologies',
            field=models.CharField(blank=True, choices=[('Html', 'Html'), ('Css', 'Css'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('C#', 'C#'), ('Python', 'Python'), ('Java', 'Java')], max_length=100, null=True),
        ),
    ]
