# Generated by Django 4.2.6 on 2023-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Register', '0002_alter_user_gender_alter_user_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Person'),
        ),
    ]
