# Generated by Django 4.2.6 on 2023-10-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Register', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='locate',
            field=models.CharField(choices=[('Acre - Rio Branco', 'Acre - Rio Branco'), ('Alagoas - Maceió', 'Alagoas - Maceió'), ('Amapá - Macapá', 'Amapá - Macapá'), ('Amazonas - Manaus', 'Amazonas - Manaus'), ('Bahia - Salvador', 'Bahia - Salvador'), ('Ceará - Fortaleza', 'Ceará - Fortaleza'), ('Espírito Santo - Vitória', 'Espírito Santo - Vitória'), ('Goiás - Goiânia', 'Goiás - Goiânia'), ('Maranhão - São Luís', 'Maranhão - São Luís'), ('Mato Grosso - Cuiabá', 'Mato Grosso - Cuiabá'), ('Mato Grosso do Sul - Campo Grande', 'Mato Grosso do Sul - Campo Grande'), ('Minas Gerais - Belo Horizonte', 'Minas Gerais - Belo Horizonte'), ('Paraíba - João Pessoa', 'Paraíba - João Pessoa'), ('Pernambuco - Recife', 'Pernambuco - Recife'), ('Piauí - Teresina', 'Piauí - Teresina'), ('Rio de Janeiro - Rio de Janeiro', 'Rio de Janeiro - Rio de Janeiro'), ('Rio Grande do Norte - Natal', 'Rio Grande do Norte - Natal'), ('Rio Grande do Sul - Porto Alegre', 'Rio Grande do Sul - Porto Alegre'), ('Rondônia - Porto Velho', 'Rondônia - Porto Velho'), ('Roraima - Boa Vista', 'Roraima - Boa Vista'), ('Santa Catarina - Florianópolis', 'Santa Catarina - Florianópolis'), ('São Paulo - São Paulo', 'São Paulo - São Paulo'), ('Sergipe - Aracaju', 'Sergipe - Aracaju'), ('Tocantins - Palmas', 'Tocantins - Palmas'), ('Distrito Federal - Brasília', 'Distrito Federal - Brasília')], default='Not Registered', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(choices=[('Studying', 'Studying'), ('Working', 'Working'), ('Freelancer', 'Freelancer'), ('Unemployed', 'Unemployed')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('Font-end', 'Front-end'), ('Back-end', 'Back-end'), ('Full-Stack', 'Full-Stack'), ('Intern', 'Intern'), ('C.Security', 'C.Security')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='technologies',
            field=models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('C#', 'C#'), ('Java', 'Java')], default=None, max_length=100, null=True),
        ),
    ]
